/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Cliente;
import Classes.Produto;
import Classes.Venda;
import DAO.CategoriaDAO;
import DAO.ClienteDAO;
import DAO.ErpDAOException;
import DAO.FornecedorDAO2;
import DAO.ProdutoDAO;
import DAO.VendaDAO;
import static java.lang.String.format;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Juliana
 */
public class InsereVenda extends javax.swing.JFrame {

    private static ArrayList<Produto> produtos = new ArrayList<Produto>();
    private static ArrayList<Cliente> clientes = new ArrayList<Cliente>();
    private static ArrayList<Venda> vendas = new ArrayList<Venda>();
    private static int posiMed, posiPac;
    private static int idpac, idmed;

    public InsereVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BT_cancelar = new javax.swing.JButton();
        TF_hora2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CB_medico = new javax.swing.JComboBox();
        CB_paciente = new javax.swing.JComboBox();
        BT_confirmar = new javax.swing.JButton();
        TF_hora1 = new javax.swing.JTextField();
        DC = new datechooser.beans.DateChooserPanel();
        jLabel5 = new javax.swing.JLabel();
        TF_hora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(103, 190, 253));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(103, 190, 253));

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Selecione a data:");

        BT_cancelar.setBackground(new java.awt.Color(189, 234, 255));
        BT_cancelar.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        BT_cancelar.setText("Voltar");
        BT_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_cancelarActionPerformed(evt);
            }
        });

        TF_hora2.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        TF_hora2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total:");

        CB_medico.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        CB_medico.setToolTipText("");
        CB_medico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_medicoItemStateChanged(evt);
            }
        });

        CB_paciente.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        CB_paciente.setToolTipText("");
        CB_paciente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_pacienteItemStateChanged(evt);
            }
        });

        BT_confirmar.setBackground(new java.awt.Color(51, 204, 0));
        BT_confirmar.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        BT_confirmar.setText("Inserir");
        BT_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_confirmarActionPerformed(evt);
            }
        });

        TF_hora1.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        TF_hora1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DC.setCurrentView(new datechooser.view.appearance.AppearancesList("custom",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    DC.setNavigateFont(new java.awt.Font("SF Pro Display", java.awt.Font.BOLD, 18));
    DC.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            DCOnSelectionChange(evt);
        }
    });

    jLabel5.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("Selecione o produto:");

    TF_hora.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
    TF_hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    jLabel6.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel6.setText("Selecione o cliente:");

    jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Quantidade:");

    jLabel7.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel7.setText("Inserção de vendas");

    jLabel8.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel8.setText("Hora: (hh:mm:ss)");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BT_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BT_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8)
                                .addComponent(jLabel1)
                                .addComponent(CB_medico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(CB_paciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TF_hora1)
                                .addComponent(jLabel9)
                                .addComponent(TF_hora2)
                                .addComponent(TF_hora)
                                .addComponent(DC, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(131, 131, 131)
                    .addComponent(jLabel7)))
            .addContainerGap(117, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(jLabel7)
            .addGap(76, 76, 76)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(CB_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(7, 7, 7)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(CB_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(TF_hora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel9)
            .addGap(12, 12, 12)
            .addComponent(TF_hora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(TF_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(DC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(BT_cancelar)
                .addComponent(BT_confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(51, 51, 51))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_medicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_medicoItemStateChanged
        posiMed = (int) CB_medico.getSelectedIndex();
        idmed = clientes.get(posiMed).getCliente_id();
    }//GEN-LAST:event_CB_medicoItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaComboCliente();
        try {
            carregaComboProduto();
        } catch (ErpDAOException ex) {
            Logger.getLogger(InsereVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void BT_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_confirmarActionPerformed

        Venda C = new Venda();
        float total = 0;
        int quantidade = 0;

        Calendar date = DC.getSelectedDate();
        total = Float.parseFloat(TF_hora2.getText());
        quantidade = Integer.parseInt(TF_hora1.getText());
        Produto produto = produtos.get(posiPac);
        int novaQuantidade = produto.getQuantidade_estoque() - quantidade;
        try {
            ProdutoDAO produtoDAO = new ProdutoDAO();
            produtoDAO.atualizarQuantidade(produto.getProduto_id(), novaQuantidade);
        } catch (ErpDAOException ex) {
            Logger.getLogger(InsereVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        C.setCliente_id(idmed);
        C.setProduto_id(idpac);
        String datas = (date.get(Calendar.DAY_OF_MONTH) + "/" + date.get(Calendar.MONTH) + "/" + date.get(Calendar.YEAR));
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date data = dtOutput.parse(datas);
            C.setData_venda(data);
        } catch (ParseException ex) {
            Logger.getLogger(InsereVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        String hora = TF_hora.getText();
        SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
        Time time;
        try {
            time = new Time(format.parse(hora).getTime());
            C.setHorario(time);
        } catch (ParseException ex) {
            Logger.getLogger(InsereVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        C.setTotal(total);
        C.setQuantidade(quantidade);
        try {
            VendaDAO pdao = new VendaDAO();
            pdao.inserir(C);
            JOptionPane.showMessageDialog(rootPane, "Inserção efetuada com sucesso!!");
        } catch (Exception ex) {
            Logger.getLogger(InsereVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();

    }//GEN-LAST:event_BT_confirmarActionPerformed

    private void CB_pacienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_pacienteItemStateChanged
        posiPac = (int) CB_paciente.getSelectedIndex();
        idpac = produtos.get(posiPac).getProduto_id();
        //T.setText(posiPac+"");
    }//GEN-LAST:event_CB_pacienteItemStateChanged

    private void DCOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_DCOnSelectionChange

    }//GEN-LAST:event_DCOnSelectionChange

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void BT_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BT_cancelarActionPerformed

    public static void carregaComboProduto() throws ErpDAOException {
        CB_paciente.removeAllItems();
        ProdutoDAO PDAO = new ProdutoDAO();
        produtos = PDAO.listar();

        for (int i = 0; i < produtos.size(); i++) {
            CB_paciente.addItem(produtos.get(i).getNome());

        }
    }

    public static void carregaComboCliente() {
        //try {
        CB_medico.removeAllItems();
        ClienteDAO MDAO = new ClienteDAO();
        clientes = MDAO.listar();
        //} catch (ErpDAOException ex) {
        // System.out.println("problema");
        // }

        for (int i = 0; i < clientes.size(); i++) {
            CB_medico.addItem(clientes.get(i).getNome());

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_cancelar;
    private javax.swing.JButton BT_confirmar;
    private static javax.swing.JComboBox CB_medico;
    private static javax.swing.JComboBox CB_paciente;
    private datechooser.beans.DateChooserPanel DC;
    private javax.swing.JTextField TF_hora;
    private javax.swing.JTextField TF_hora1;
    private javax.swing.JTextField TF_hora2;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private JTextArea setString(String date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
