/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Categoria;
import Classes.Fornecedor;
import Classes.Produto;
import DAO.CategoriaDAO;
import DAO.FornecedorDAO;
import DAO.ErpDAOException;
import DAO.FornecedorDAO2;
import DAO.ProdutoDAO;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author 287792
 */
public class InsereProduto extends javax.swing.JFrame {

    private static ArrayList<Categoria> CategoriaS = new ArrayList<Categoria>();
    private static ArrayList<Fornecedor> Fornecedores = new ArrayList<Fornecedor>();
    private static int codigo = 0;
    private static int posicao = 0;

    /**
     * Creates new form InsereProduto
     */
    public InsereProduto() {
        initComponents();
    }

    InsereProduto(int codigo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcombobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jnome = new javax.swing.JTextField();
        jpreco = new javax.swing.JTextField();
        jquantidade = new javax.swing.JTextField();
        jButtonp = new javax.swing.JButton();
        jButtonopa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jcombobox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(103, 190, 253));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel1.setText("Inserção de Produtos");

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jcombobox.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jcombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboboxItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel3.setText("Selecione a categoria:");

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel4.setText("Quantidade:");

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel5.setText("Preço:");

        jnome.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jnome.setPreferredSize(new java.awt.Dimension(64, 31));
        jnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnomeActionPerformed(evt);
            }
        });

        jpreco.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jpreco.setPreferredSize(new java.awt.Dimension(64, 31));
        jpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprecoActionPerformed(evt);
            }
        });

        jquantidade.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jquantidade.setPreferredSize(new java.awt.Dimension(64, 31));
        jquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jquantidadeActionPerformed(evt);
            }
        });

        jButtonp.setBackground(new java.awt.Color(51, 204, 0));
        jButtonp.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jButtonp.setText("Inserir");
        jButtonp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonpMouseClicked(evt);
            }
        });

        jButtonopa.setBackground(new java.awt.Color(189, 234, 255));
        jButtonopa.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jButtonopa.setText("Voltar");
        jButtonopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonopaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel8.setText("Selecione o fornecedor:");

        jcombobox2.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonopa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(jButtonp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jcombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jnome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jquantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcombobox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcombobox2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonp)
                    .addComponent(jButtonopa))
                .addGap(33, 33, 33))
        );

        jcombobox.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnomeActionPerformed

    private void jprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jprecoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        carregaCombo();
        carregaCombo2();
    }//GEN-LAST:event_formWindowActivated

    private void jcomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboboxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboboxItemStateChanged

    private void jquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jquantidadeActionPerformed

    private void jButtonopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonopaActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonopaActionPerformed

    private void jButtonpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonpMouseClicked
        String nome = null;
        int quantidade_estoque, fornecedor_id, categoria_id = 0;
        float preco;

        nome = jnome.getText();
        preco = Float.parseFloat(jpreco.getText());
        quantidade_estoque = Integer.parseInt(jquantidade.getText());
        categoria_id = (int) jcombobox.getSelectedIndex()+1;
        fornecedor_id = (int) jcombobox2.getSelectedIndex()+1;

        P.setNome(nome);
        P.setPreco(preco);
        P.setQuantidade_estoque(quantidade_estoque);
        P.setCategoria_id(categoria_id);
        P.setFornecedor_id(fornecedor_id);

        try {
            ProdutoDAO PDAO = new ProdutoDAO();
            PDAO.inserir(P);
            JOptionPane.showMessageDialog(rootPane, "Inserção efetuada com sucesso!!");
        } catch (ErpDAOException ex) {
            System.out.println("problema na inserção do contato");
        }

        dispose();


    }//GEN-LAST:event_jButtonpMouseClicked
    public static void carregaCombo() {
        try {
            jcombobox.removeAllItems();
            CategoriaDAO MDAO = new CategoriaDAO();
            CategoriaS = MDAO.listar();
        } catch (ErpDAOException ex) {
            System.out.println("problema");
        }

        for (int i = 0; i < CategoriaS.size(); i++) {
            jcombobox.addItem(CategoriaS.get(i).getNome());

        }
    }

    public static void carregaCombo2() {
        try {
            jcombobox2.removeAllItems();
            FornecedorDAO2 FDAO = new FornecedorDAO2();
            Fornecedores = FDAO.listar();
        } catch (Exception ex) {
            System.out.println("problema");
        }

        for (int i = 0; i < Fornecedores.size(); i++) {
            jcombobox2.addItem(Fornecedores.get(i).getNome());

        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonopa;
    private javax.swing.JButton jButtonp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JComboBox<String> jcombobox;
    private static javax.swing.JComboBox<String> jcombobox2;
    private javax.swing.JTextField jnome;
    private javax.swing.JTextField jpreco;
    private javax.swing.JTextField jquantidade;
    // End of variables declaration//GEN-END:variables
  private Produto P = new Produto();
}
